name: Swift

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: swift test --enable-code-coverage
