name: ci-library-crypto-ios

on:
  pull_request:
    branches: [ main ]

jobs:
  test-library-crypto-ios:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
